### ISSUE TITLE
Kernel error on boot

### ISSUE THREAD

**Issue by janissammetti** [tienthanght96/Asus-Rog-Z490-G-Hackintosh#1]
I get an Kernel error on the boot of my system.
HW: Asus Rog Z490G + RX6900XT OC Gigabyte

[opencore-2021-12-01-180640.txt](https://github.com/tienthanght96/Asus-Rog-Z490-G-Hackintosh/files/7636274/opencore-2021-12-01-180640.txt)
[opencore-2021-12-01-174206.txt](https://github.com/tienthanght96/Asus-Rog-Z490-G-Hackintosh/files/7636275/opencore-2021-12-01-174206.txt)
![WhatsApp Image 2021-12-01 at 19 07 27](https://user-images.githubusercontent.com/56651485/144291006-df8a3740-cabb-475b-b272-5d682a55f77f.jpeg)
e

**Comment by tienthanght96** [comment]
If you using new OC version and ProperTree, try to using ocvalidate utils to check config.plist file. If have errors you should clean snapshot and see error messages to fix them.

**Comment by tienthanght96** [comment]
After I download and see your error message in log file **_Prelinked injection AirportItlwm.kext (AirportItlwm.kext) - Invalid Parameter_**. I think you also check your macos & kexts version.
Maybe this article will help you https://www.reddit.com/r/hackintosh/comments/nuwda0/prelinked_injection_airportitlwm_failed_invalid/
